### PR TITLE
Add support for iodine (TCP server mode)

### PR DESCRIPTION
**Pull request by boazsegev**
Hi,

Nice fun benchmark suite.

Iodine is an HTTP/WebSocket server, but it also supports raw TCP/IP communication.

Using iodine's TCP/IP mode (`raw`), I followed your example of implementing a simple HTTP response. This is by far sub-optimal, but it runs.

Feel welcome to add this to the benchmark suite.

Cheers,
   Bo.

### CODE REVIEW

**Review by jsaak — APPROVED** [review]
What does Iodine.threads = -2 mean? The desired behaviour is using 1 threads.

**Comment by boazsegev** [comment]
The `Iodine.threads = -2` means that iodine will use as many worker threads as [half the CPU cores](https://github.com/boazsegev/iodine#optimizing-iodines-concurrency).

**Comment by jsaak** [comment]
ok, then i will change it to 1, to be on par with the other benchmarks

**Comment by boazsegev** [comment]
Sure 👍🏻

I think it could actually improve performance since you're testing with a single connection anyway (`-c1`).

Thanks!
   Bo.

**Pull request merged**
